# `sheldon` configuration file
# ----------------------------
#
# You can modify this file directly or you can use one of the following
# `sheldon` commands which are provided to assist in editing the config file:
#
# - `sheldon add` to add a new plugin to the config file
# - `sheldon edit` to open up the config file in the default editor
# - `sheldon remove` to remove a plugin from the config file
#
# See the documentation for more https://github.com/rossmacarthur/sheldon#readme

shell = "zsh"

[templates]
defer = "{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}"

[plugins]
# sheldon lock --update    # プラグイン更新
# sheldon lock --reinstall # プラグイン再インストール

# プラグインを遅延読み込みする
[plugins.zsh-defer]
github = "romkatv/zsh-defer"

# コマンド履歴からサジェスト
[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
apply = ["defer"]

# [plugins.fast-syntax-highlighting]
# github = "zdharma/fast-syntax-highlighting"
# apply = ["defer"]


# git open で remote をブラウザで開く
[plugins.git-open]
github = "paulirish/git-open"
apply = ["defer"]

# git status の代わりに `k` コマンド
[plugins.k]
github = "supercrabtree/k"
apply = ["defer"]
